/*
 * OpenAPI Example
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Todo - A todo
type Todo struct {

	Id int64 `json:"id,omitempty"`

	Name string `json:"name"`

	// todo status
	// Deprecated
	Status string `json:"status,omitempty"`
}

// AssertTodoRequired checks if the required fields are not zero-ed
func AssertTodoRequired(obj Todo) error {
	elements := map[string]interface{}{
		"name": obj.Name,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseTodoRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of Todo (e.g. [][]Todo), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseTodoRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aTodo, ok := obj.(Todo)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertTodoRequired(aTodo)
	})
}
